name: appservice-plans-deploy

####################################################################
## Triggers
####################################################################
on:
  workflow_call:
    inputs:
      template_file_path: 
        required: true
        description: Path to bicep template to deploy infrastructure.
        type: string
      build_id:
        required: true
        description: Run ID to download artifact from workflow
        type: string
      workload:
        required: true
        description: Busineed workload type
        type: string
      environment:
        required: true
        description: Environment to run this workflow
        type: string
      location:
        required: true
        description: Azure location to carry out deployment
        type: string
      instance_count:
        required: true
        description: Two digit instance count for azure resources
        type: string

####################################################################
## Job
####################################################################
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      ####################################################################
      ## Download artifacts from pipeline
      ####################################################################
      - name: Downloading artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          run_id: ${{ inputs.build_id }}
      ####################################################################
      ## Login to azure
      ####################################################################
      - name: Login to azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}
      ####################################################################
      ## Running infrastructure validation
      ####################################################################
      - name: Running preflight validation
        uses: azure/arm-deploy@v1
        with:
          resourceGroupName: rg-${{ inputs.workload }}-${{ inputs.environment }}-${{ inputs.location }}-${{ inputs.instance_count }}
          template: ${{ inputs.template_file_path }}
          parameters: environment=${{ inputs.environment }} workload=${{ inputs.workload }} deploymentIdentity=${{ secrets.CLIENT_ID }}
          deploymentmode: Validate
          scope: resourcegroup
      ####################################################################
      ## Deploying infrasturcture
      ####################################################################
      - name: Deploying azure infrastructure
        uses: azure/arm-deploy@v1
        with:
          resourceGroupName: rg-${{ inputs.workload }}-${{ inputs.environment }}-${{ inputs.location }}-${{ inputs.instance_count }}
          template: ${{ inputs.template_file_path }}
          parameters: environment=${{ inputs.environment }} workload=${{ inputs.workload }} deploymentIdentity=${{ secrets.CLIENT_ID }}
          deploymentmode: Complete
          scope: resourcegroup
