name: appservice-plans-nonproduction

####################################################################
## Triggers
####################################################################
on:
  workflow_dispatch:
    inputs:
      build_id:
        description: build workflow id to pick artifacts and deploy
        required: true

####################################################################
## Permissions
####################################################################
permissions:
  id-token: write
  contents: write
  actions: read

####################################################################
## Jobs
####################################################################
jobs:
  deploy:
    uses: fbitn/az-appservice-plans/.github/workflows/deploy.yml@main
    with:
      template_file_path: infrastructure/main.bicep
      build_id: ${{ inputs.build_id }}
      workload: appserviceplans
      environment: np
      location: eastus2
      instance_count: "01"
    secrets: inherit
